---
- name: install k8s
  hosts: k8s
  tags: k8s_install
  tasks:
    # This create test dir for storing the group/host test files.
    # Skip if the dir exists.
    - git: 
        repo: 'https://github.com/kubernetes/kubernetes.git'
#        dest: /home/root/k8s/
        dest: "{{ git_dir }}"

- name: config k8s
  hosts: k8s
  tags: k8s_config
  tasks:
    - shell: "cd {{ git_dir }}; git checkout release-1.6"
    - template:
        src: 'template/config-default.sh'
        dest: '{{ git_dir }}/cluster/{{ KUBERNETES_PROVIDER }}/config-default.sh'

- name: backup k8s installation dir
  hosts: k8s
  tags: backup
  tasks:
    - shell: "cp -rf {{ git_dir }} {{ git_dir }}.bak"

- name: restore k8s installation dir
  hosts: k8s
  tags: restore
  tasks:
    - shell: "mv {{ git_dir }} {{ git_dir }}.old; cp -rf {{ git_dir }}.bak {{ git_dir }}"
