---
- name: download k8s
  hosts: master
  tags: k8s_download
  tasks:
    # This create test dir for storing the group/host test files.
    # Skip if the dir exists.
    - git: 
        repo: 'https://github.com/kubernetes/kubernetes.git'
#        dest: /home/root/k8s/
        dest: "{{ git_dir }}"

- name: config k8s
  hosts: master
  tags: k8s_config
  tasks:
    - shell: "cd {{ git_dir }}; git checkout release-1.6"
    - template:
        src: 'template/config-default.sh'
        dest: '{{ git_dir }}/cluster/{{ KUBERNETES_PROVIDER }}/config-default.sh'

- name: backup k8s installation dir
  hosts: master
  tags: backup
  tasks:
    - shell: "cp -rTf {{ git_dir }} {{ git_dir }}.bak"
      when: backup == "true"

- name: restore k8s installation dir
  hosts: master
  tags: restore
  tasks:
    - shell: "mv {{ git_dir }} {{ git_dir }}.old; cp -rfT {{ git_dir }}.bak {{ git_dir }}"
      when: restore == "true"

- name: install k8s
  hosts: master
  tags: install
  tasks:
#    - shell: "KUBERNETES_PROVIDER={{ KUBERNETES_PROVIDER }} ; bash {{ git_dir }}/cluster/kube-up.sh"
    - shell: "export KUBERNETES_PROVIDER=ubuntu ; yes | bash {{ git_dir }}/cluster/kube-up.sh"

